### ISSUE TITLE
Requires SystemD???

### ISSUE THREAD

**Issue by kenny-wettlaufer** [hakerdefo/lepo-logout#1]
Why does this thing require a specific init system? Kind of silly if you ask me.

**Comment by hakerdefo** [comment]
@kenny-wettlaufer **lepo-logout** utilises the **systemd** components for the tasks of Logout, Suspend, Reboot & Shutdown the system. May be not so silly if you consider the percentage of Linux distributions using the **systemd** as their default **init** system.
